apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-cronjob
spec:
  schedule: "*/1 * * * *"   # every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date
            image: busybox
            command: ["date"]
          restartPolicy: Never
