apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
    - name: cpu-container
      image: nginx
      resources:
        requests:
          cpu: "100m"       # Minimum CPU the pod needs to be scheduled
        limits:
          cpu: "200m"       # Maximum CPU the pod is allowed to use
